# KeyError

my_dict = {
    "name": "Kevin",
    "surname": "Schans",
    "age": 29,
    "tech": "Python"
}

print(my_dict["names"]) # KeyError: 'names'
